output:
  format: colored-line-number
linters-settings:
  enable:
  - stylecheck
  - unconvert
  - gosec
  - errorlint
  - maligned
  - interfacer
  - unparam
  - whitespace
  - wrapcheck
  - prealloc
  - nolintlint
run:
  timeout: "1m"
  issue-exit-code: 1
  tests: false
