## See https://pre-commit.com for more information
## See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
    args:
    - --assume-in-merge
  - id: check-vcs-permalinks
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-private-key
  # - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  # - id: no-commit-to-branch
  - id: trailing-whitespace
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.7.3
  hooks:
  - id: editorconfig-checker
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.39.0
  hooks:
  - id: markdownlint
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.1-beta
  hooks:
  - id: hadolint
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-mod-tidy
    name: go mod tidy
  - id: golangci-lint-repo-mod
    name: golangci-lint
  - id: go-build-repo-mod
    name: go build
    args:
    - -race
    - -mod=mod
  # custom go test as bouk doesn't support arm64
  - id: my-cmd-repo
    name: go test
    args:
    - env
    - GOARCH=amd64
    - go
    - test
    - -race
    - -ldflags=-s=false
    - -gcflags=all=-l
    - ./...
- repo: local
  hooks:
  - id: syft-grype
    name: syft-grype scan
    language: script
    entry: .github/scripts/syft-grype.sh
    args:
    - dir:.
    pass_filenames: false
ci:
  skip:
  - hadolint
  - golangci-lint-repo-mod
  - go-mod-tidy
  - go-build-repo-mod
  - go-test-repo-mod
  - syft-grype
